### Post a new user
POST localhost:8080/api/traveler/register
Content-Type: application/json

{
  "username": "test",
  "email": "test@test.com",
  "password": "12345"
}

### Login with the new user
POST localhost:8080/api/traveler/login
Content-Type: application/json

{
"email": "test@test.com",
"password": "12345"
}

> {% client.global.set("token", response.body.token) %}


